name: Validate branch name
on: [push, pull_request]

env:
  forbidden_branches: 'add-actions master'

jobs:
  comment:
    runs-on: ubuntu-latest
    steps:
      - name: Run Tests
        env:
          RACK_ENV: test
        run: |
          echo "A branch cannot be named ${{ github.ref }} because it is in the list of forbidden branch names, which is: ${{ env.forbidden_branches}}" 
          exit 1
